//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            ImagePro = "~/Content/images/1298880.png";
        }
        [NotMapped]
        public HttpPostedFileBase UploadImage { get; set; }

        public int ProductID { get; set; }

        [Required(ErrorMessage = "Tên sản phẩm không được để trống")]
        public string NamePro { get; set; }

        [Required(ErrorMessage = "Mô tả ngắn không được để trống")]
        public string DecriptionSmall { get; set; }

        [Required(ErrorMessage = "Danh mục không được để trống")]
        public string Category { get; set; }

        [Required(ErrorMessage = "Giá sản phẩm không được để trống")]
        [Range(0, double.MaxValue, ErrorMessage = "Giá sản phẩm phải là số dương")]

        public Nullable<decimal> Price { get; set; }
        public string ImagePro { get; set; }
        public Nullable<int> RemainQuantity { get; set; }
        public Nullable<int> SoldQuantity { get; set; }
        [Required(ErrorMessage = "Nhà cung cấp không được để trống")]
        public string Supplier { get; set; }
        [Required(ErrorMessage = "Tác giả không được để trống")]
        public string Author { get; set; }
        [Required(ErrorMessage = "Nhà xuất bản không được để trống")]
        public string Publisher { get; set; }
        [Required(ErrorMessage = "Năm xuất bản không được để trống")]
        [Range(1000, 2026, ErrorMessage = "Năm xuất bản không hợp lệ")]
        public Nullable<int> Publishingyear { get; set; }
        [Required(ErrorMessage = "Ngôn ngữ không được để trống")]
        public string C_Language { get; set; }
        [Required(ErrorMessage = "Series không được để trống")]
        public string Series { get; set; }

        [Required(ErrorMessage = "Số lượng không được để trống")]
        [Range(0, int.MaxValue, ErrorMessage = "Số lượng phải là số dương")]
        public Nullable<int> Quantity { get; set; }
        [Required(ErrorMessage = "Mô tả chi tiết không được để trống")]
        public string DescriptionBig { get; set; }
        public string NamePub { get; set; }
        public string NameSub { get; set; }
    
        public virtual Category Category1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual Publisher Publisher1 { get; set; }
        public virtual Supplier Supplier1 { get; set; }
    }
}
